import { TrendingUp, Settings, Zap } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { api } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";
import { useMutation, useQueryClient } from "@tanstack/react-query";

export function MarketUpdates() {
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const generateMutation = useMutation({
    mutationFn: api.generateMarketSummary,
    onSuccess: async (result) => {
      // Create a content post with the generated summary
      await api.createContentPost({
        type: 'market',
        title: result.title,
        content: result.content,
        originalContent: null,
        aiEnhanced: result.enhanced,
        platforms: ['telegram', 'twitter'],
        status: 'draft',
        scheduledAt: null,
      });
      
      queryClient.invalidateQueries({ queryKey: ['/api/content-posts'] });
      queryClient.invalidateQueries({ queryKey: ['/api/stats'] });
      
      toast({
        title: "Market summary generated",
        description: "New market update has been created and saved as draft.",
      });
    },
    onError: (error) => {
      toast({
        title: "Generation failed",
        description: error.message,
        variant: "destructive",
      });
    },
    onSettled: () => {
      setIsGenerating(false);
    },
  });

  const handleGenerate = () => {
    setIsGenerating(true);
    generateMutation.mutate();
  };

  return (
    <div className="bg-white rounded-xl shadow-sm border border-slate-200">
      <div className="p-6 border-b border-slate-200">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-emerald-100 rounded-lg flex items-center justify-center">
              <TrendingUp className="w-5 h-5 text-emerald-600" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-slate-900">Market Updates</h3>
              <p className="text-sm text-slate-600">AI-powered market summaries</p>
            </div>
          </div>
          <Button variant="ghost" size="sm">
            <Settings className="w-4 h-4 mr-2" />
            Configure
          </Button>
        </div>
      </div>
      
      <div className="p-6">
        <div className="space-y-4">
          <div className="p-4 bg-emerald-50 rounded-lg border border-emerald-200">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <h4 className="font-medium text-slate-900">Daily Market Summary</h4>
                <p className="text-sm text-slate-600 mt-1">Generated by AI • Last updated 2 hours ago</p>
                <p className="text-sm text-slate-700 mt-3 leading-relaxed">
                  "Markets opened higher today as tech stocks rallied on strong earnings reports. The S&P 500 gained 1.2% while the Nasdaq climbed 1.8%. Key movers include AAPL (+2.3%) and MSFT (+1.9%)..."
                </p>
              </div>
              <div className="ml-4">
                <Badge className="bg-green-100 text-green-800">Posted</Badge>
              </div>
            </div>
          </div>
          
          <div className="p-4 bg-slate-50 rounded-lg">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <h4 className="font-medium text-slate-900">Weekly Outlook</h4>
                <p className="text-sm text-slate-600 mt-1">Scheduled for Monday 9:00 AM</p>
                <p className="text-sm text-slate-700 mt-3 leading-relaxed">
                  "Next week brings important economic data including CPI inflation figures and Fed meeting minutes. Analysts expect continued volatility in tech sector..."
                </p>
              </div>
              <div className="ml-4">
                <Badge className="bg-yellow-100 text-yellow-800">Scheduled</Badge>
              </div>
            </div>
          </div>
        </div>
        
        <div className="mt-6 flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <span className="text-sm text-slate-600">GPT-4 Integration</span>
            </div>
            <span className="text-sm text-slate-500">•</span>
            <span className="text-sm text-slate-600">Daily at 9:00 AM</span>
          </div>
          <Button 
            variant="ghost" 
            size="sm"
            onClick={handleGenerate}
            disabled={isGenerating}
          >
            <Zap className="w-4 h-4 mr-2" />
            {isGenerating ? 'Generating...' : 'Generate Now'}
          </Button>
        </div>
      </div>
    </div>
  );
}
