# Generated by Django 4.2.20 on 2025-05-11 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_html', models.TextField(help_text='The raw HTML content that was scraped')),
                ('content_text', models.TextField(blank=True, help_text='The processed text content')),
                ('scrape_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_url', models.URLField(help_text='URL where the data was scraped from')),
            ],
            options={
                'verbose_name': 'Scraped Data',
                'verbose_name_plural': 'Scraped Data',
                'ordering': ['-scrape_date'],
            },
        ),
    ]
