# Generated by Django 4.2.20 on 2025-05-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_scrapeddata_is_processed_scrapeddata_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapeddata',
            options={'ordering': ['-scrape_date'], 'verbose_name': 'Forex Signal', 'verbose_name_plural': 'Forex Signals'},
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='action',
            field=models.CharField(blank=True, help_text='Buy or Sell signal', max_length=10),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='entry_price',
            field=models.CharField(blank=True, help_text='Entry price for the signal', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='instrument',
            field=models.CharField(blank=True, help_text='Forex pair or instrument', max_length=50),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='status_signal',
            field=models.CharField(blank=True, help_text='Signal status (Active, Closed, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='stop_loss',
            field=models.CharField(blank=True, help_text='Stop loss price', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='take_profit',
            field=models.CharField(blank=True, help_text='Take profit price', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='content_html',
            field=models.TextField(blank=True, help_text='The raw HTML content of the forex signal', null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='content_text',
            field=models.TextField(help_text='The formatted text representation of the forex signal'),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='is_processed',
            field=models.BooleanField(default=True, help_text='Whether the signal has been processed'),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='source_url',
            field=models.URLField(help_text='FX Leaders URL where the signal was scraped from'),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='success', help_text='Status of the scraping operation', max_length=10),
        ),
    ]
